ERROR - 2025-08-19 13:09:37 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\MySQLi\Connection.php:202
Stack trace:
#0 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\MySQLi\Connection.php(202): mysqli->real_connect('localhost', 'root', '', 'san_miguel_hms', 3306, '', 0)
#1 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#4 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\BaseConnection.php(1545): CodeIgniter\Database\BaseConnection->listTables()
#5 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\MigrationRunner.php(768): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#6 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\MigrationRunner.php(162): CodeIgniter\Database\MigrationRunner->ensureTable()
#7 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\WEB_ITE_GROUP4\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\WEB_ITE_GROUP4\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#11 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\xampp\htdocs\WEB_ITE_GROUP4\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#3 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\BaseConnection.php(1545): CodeIgniter\Database\BaseConnection->listTables()
#4 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\MigrationRunner.php(768): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#5 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\MigrationRunner.php(162): CodeIgniter\Database\MigrationRunner->ensureTable()
#6 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#7 C:\xampp\htdocs\WEB_ITE_GROUP4\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#8 C:\xampp\htdocs\WEB_ITE_GROUP4\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#9 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#10 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#11 C:\xampp\htdocs\WEB_ITE_GROUP4\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-08-19 13:13:15 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/add_patient.php"
[Method: GET, Route: patients/add]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/add_patient.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/add_patient', [], true)
 3 APPPATH\Controllers\Patients.php(19): view('auth/add_patient')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Patients->add()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Patients))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-19 14:21:04 --> mysqli_sql_exception: Unknown column 'notes' in 'field list' in C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `ap...', 0)
#1 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ap...')
#2 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ap...')
#3 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ap...', Array, false)
#4 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\WEB_ITE_GROUP4\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\WEB_ITE_GROUP4\app\Controllers\Appointments.php(59): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\WEB_ITE_GROUP4\system\CodeIgniter.php(933): App\Controllers\Appointments->store()
#9 C:\xampp\htdocs\WEB_ITE_GROUP4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
#10 C:\xampp\htdocs\WEB_ITE_GROUP4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\WEB_ITE_GROUP4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-08-19 14:21:04 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'notes' in 'field list'
[Method: POST, Route: appointments/store]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `appointments` (`appointment_code`, `patient_name`, `patient_phone`, `doctor_name`, `date_time`, `type`, `status`, `notes`, `created_at`, `updated_at`) VALUES (:appointment_code:, :patient_name:, :patient_phone:, :doctor_name:, :date_time:, :type:, :status:, :notes:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Appointments.php(59): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Appointments->store()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-19 14:21:04 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'notes' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `appointments` (`appointment_code`, `patient_name`, `patient_phone`, `doctor_name`, `date_time`, `type`, `status`, `notes`, `created_at`, `updated_at`) VALUES (NULL, \'yad hehe\', NULL, \'meow\', \'2025-08-19 11:11\', \'Follow-up\', \'Confirmed\', \'hhhhh\', \'2025-08-19 14:21:04\', \'2025-08-19 14:21:04\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `appointments` (`appointment_code`, `patient_name`, `patient_phone`, `doctor_name`, `date_time`, `type`, `status`, `notes`, `created_at`, `updated_at`) VALUES (NULL, \'yad hehe\', NULL, \'meow\', \'2025-08-19 11:11\', \'Follow-up\', \'Confirmed\', \'hhhhh\', \'2025-08-19 14:21:04\', \'2025-08-19 14:21:04\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `appointments` (`appointment_code`, `patient_name`, `patient_phone`, `doctor_name`, `date_time`, `type`, `status`, `notes`, `created_at`, `updated_at`) VALUES (:appointment_code:, :patient_name:, :patient_phone:, :doctor_name:, :date_time:, :type:, :status:, :notes:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Appointments.php(59): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Appointments->store()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-19 14:21:04 --> [Caused by] mysqli_sql_exception: Unknown column 'notes' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `appointments` (`appointment_code`, `patient_name`, `patient_phone`, `doctor_name`, `date_time`, `type`, `status`, `notes`, `created_at`, `updated_at`) VALUES (NULL, \'yad hehe\', NULL, \'meow\', \'2025-08-19 11:11\', \'Follow-up\', \'Confirmed\', \'hhhhh\', \'2025-08-19 14:21:04\', \'2025-08-19 14:21:04\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `appointments` (`appointment_code`, `patient_name`, `patient_phone`, `doctor_name`, `date_time`, `type`, `status`, `notes`, `created_at`, `updated_at`) VALUES (NULL, \'yad hehe\', NULL, \'meow\', \'2025-08-19 11:11\', \'Follow-up\', \'Confirmed\', \'hhhhh\', \'2025-08-19 14:21:04\', \'2025-08-19 14:21:04\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `appointments` (`appointment_code`, `patient_name`, `patient_phone`, `doctor_name`, `date_time`, `type`, `status`, `notes`, `created_at`, `updated_at`) VALUES (NULL, \'yad hehe\', NULL, \'meow\', \'2025-08-19 11:11\', \'Follow-up\', \'Confirmed\', \'hhhhh\', \'2025-08-19 14:21:04\', \'2025-08-19 14:21:04\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `appointments` (`appointment_code`, `patient_name`, `patient_phone`, `doctor_name`, `date_time`, `type`, `status`, `notes`, `created_at`, `updated_at`) VALUES (:appointment_code:, :patient_name:, :patient_phone:, :doctor_name:, :date_time:, :type:, :status:, :notes:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Appointments.php(59): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Appointments->store()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-19 14:21:15 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/appointment_edit.php"
[Method: GET, Route: appointments/edit/1]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/appointment_edit.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/appointment_edit', [], true)
 3 APPPATH\Controllers\Appointments.php(93): view('auth/appointment_edit', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Appointments->edit('1')
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-19 14:25:39 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/appointment_view.php"
[Method: GET, Route: appointments/view/1]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/appointment_view.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/appointment_view', [], true)
 3 APPPATH\Controllers\Appointments.php(86): view('auth/appointment_view', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Appointments->view('1')
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-19 14:25:43 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/appointment_edit.php"
[Method: GET, Route: appointments/edit/1]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/appointment_edit.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/appointment_edit', [], true)
 3 APPPATH\Controllers\Appointments.php(93): view('auth/appointment_edit', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Appointments->edit('1')
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-19 14:25:48 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/appointment_edit.php"
[Method: GET, Route: appointments/edit/1]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/appointment_edit.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/appointment_edit', [], true)
 3 APPPATH\Controllers\Appointments.php(93): view('auth/appointment_edit', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Appointments->edit('1')
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-19 14:25:54 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/view_patient.php"
[Method: GET, Route: patients/view/1]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/view_patient.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/view_patient', [], true)
 3 APPPATH\Controllers\Patients.php(25): view('auth/view_patient', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Patients->view('1')
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Patients))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-19 14:25:58 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/edit_patient.php"
[Method: GET, Route: patients/edit/1]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/edit_patient.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/edit_patient', [], true)
 3 APPPATH\Controllers\Patients.php(65): view('auth/edit_patient', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Patients->edit('1')
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Patients))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-19 14:29:41 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/view_patient.php"
[Method: GET, Route: patients/view/1]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/view_patient.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/view_patient', [], true)
 3 APPPATH\Controllers\Patients.php(25): view('auth/view_patient', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Patients->view('1')
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Patients))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-19 14:43:07 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/view_patient.php"
[Method: GET, Route: patients/view/1]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/view_patient.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/view_patient', [], true)
 3 APPPATH\Controllers\Patients.php(25): view('auth/view_patient', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Patients->view('1')
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Patients))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-19 14:49:17 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/appointment_edit.php"
[Method: GET, Route: appointments/edit/1]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/appointment_edit.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/appointment_edit', [], true)
 3 APPPATH\Controllers\Appointments.php(93): view('auth/appointment_edit', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Appointments->edit('1')
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-19 14:59:26 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/appointment_edit.php"
[Method: GET, Route: appointments/edit/1]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/appointment_edit.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/appointment_edit', [], true)
 3 APPPATH\Controllers\Appointments.php(93): view('auth/appointment_edit', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Appointments->edit('1')
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-19 14:59:30 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/appointment_view.php"
[Method: GET, Route: appointments/view/1]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/appointment_view.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/appointment_view', [], true)
 3 APPPATH\Controllers\Appointments.php(86): view('auth/appointment_view', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Appointments->view('1')
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-19 14:59:43 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/appointment_view.php"
[Method: GET, Route: appointments/view/1]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/appointment_view.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/appointment_view', [], true)
 3 APPPATH\Controllers\Appointments.php(86): view('auth/appointment_view', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Appointments->view('1')
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-19 15:07:24 --> mysqli_sql_exception: Unknown column 'notes' in 'field list' in C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `appoint...', 0)
#1 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `appoint...')
#2 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `appoint...')
#3 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `appoint...', Array, false)
#4 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\WEB_ITE_GROUP4\system\BaseModel.php(1025): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Model.php(860): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\WEB_ITE_GROUP4\app\Controllers\Appointments.php(106): CodeIgniter\Model->update('1', Array)
#8 C:\xampp\htdocs\WEB_ITE_GROUP4\system\CodeIgniter.php(933): App\Controllers\Appointments->update('1')
#9 C:\xampp\htdocs\WEB_ITE_GROUP4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
#10 C:\xampp\htdocs\WEB_ITE_GROUP4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\WEB_ITE_GROUP4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-08-19 15:07:24 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'notes' in 'field list'
[Method: POST, Route: appointments/update/1]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `appointments` SET `patient_name` = :patient_name:, `patient_phone` = :patient_phone:, `doctor_name` = :doctor_name:, `date_time` = :date_time:, `type` = :type:, `status` = :status:, `notes` = :notes:, `updated_at` = :updated_at:
WHERE `appointments`.`id` IN :appointments.id:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Appointments.php(106): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Appointments->update('1')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-19 15:07:24 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'notes' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `appointments` SET `patient_name` = NULL, `patient_phone` = NULL, `doctor_name` = \'Dr. johnson\', `date_time` = \' \', `type` = NULL, `status` = NULL, `notes` = NULL, `updated_at` = \'2025-08-19 15:07:24\'
WHERE `appointments`.`id` IN (\'1\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `appointments` SET `patient_name` = NULL, `patient_phone` = NULL, `doctor_name` = \'Dr. johnson\', `date_time` = \' \', `type` = NULL, `status` = NULL, `notes` = NULL, `updated_at` = \'2025-08-19 15:07:24\'
WHERE `appointments`.`id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `appointments` SET `patient_name` = :patient_name:, `patient_phone` = :patient_phone:, `doctor_name` = :doctor_name:, `date_time` = :date_time:, `type` = :type:, `status` = :status:, `notes` = :notes:, `updated_at` = :updated_at:
WHERE `appointments`.`id` IN :appointments.id:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\Appointments.php(106): CodeIgniter\Model->update('1', [...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Appointments->update('1')
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-19 15:07:24 --> [Caused by] mysqli_sql_exception: Unknown column 'notes' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `appointments` SET `patient_name` = NULL, `patient_phone` = NULL, `doctor_name` = \'Dr. johnson\', `date_time` = \' \', `type` = NULL, `status` = NULL, `notes` = NULL, `updated_at` = \'2025-08-19 15:07:24\'
WHERE `appointments`.`id` IN (\'1\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `appointments` SET `patient_name` = NULL, `patient_phone` = NULL, `doctor_name` = \'Dr. johnson\', `date_time` = \' \', `type` = NULL, `status` = NULL, `notes` = NULL, `updated_at` = \'2025-08-19 15:07:24\'
WHERE `appointments`.`id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `appointments` SET `patient_name` = NULL, `patient_phone` = NULL, `doctor_name` = \'Dr. johnson\', `date_time` = \' \', `type` = NULL, `status` = NULL, `notes` = NULL, `updated_at` = \'2025-08-19 15:07:24\'
WHERE `appointments`.`id` IN (\'1\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `appointments` SET `patient_name` = :patient_name:, `patient_phone` = :patient_phone:, `doctor_name` = :doctor_name:, `date_time` = :date_time:, `type` = :type:, `status` = :status:, `notes` = :notes:, `updated_at` = :updated_at:
WHERE `appointments`.`id` IN :appointments.id:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Appointments.php(106): CodeIgniter\Model->update('1', [...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Appointments->update('1')
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-19 15:08:22 --> mysqli_sql_exception: Unknown column 'notes' in 'field list' in C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `ap...', 0)
#1 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ap...')
#2 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ap...')
#3 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ap...', Array, false)
#4 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\WEB_ITE_GROUP4\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\WEB_ITE_GROUP4\app\Controllers\Appointments.php(59): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\WEB_ITE_GROUP4\system\CodeIgniter.php(933): App\Controllers\Appointments->store()
#9 C:\xampp\htdocs\WEB_ITE_GROUP4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
#10 C:\xampp\htdocs\WEB_ITE_GROUP4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\WEB_ITE_GROUP4\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\WEB_ITE_GROUP4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-08-19 15:08:22 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'notes' in 'field list'
[Method: POST, Route: appointments/store]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `appointments` (`appointment_code`, `patient_name`, `patient_phone`, `doctor_name`, `date_time`, `type`, `status`, `notes`, `created_at`, `updated_at`) VALUES (:appointment_code:, :patient_name:, :patient_phone:, :doctor_name:, :date_time:, :type:, :status:, :notes:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Appointments.php(59): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Appointments->store()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-19 15:08:22 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'notes' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `appointments` (`appointment_code`, `patient_name`, `patient_phone`, `doctor_name`, `date_time`, `type`, `status`, `notes`, `created_at`, `updated_at`) VALUES (NULL, \'dadad\', NULL, \'meow\', \'2025-08-19 14:03\', \'Follow-up\', \'Confirmed\', \'hahahah\', \'2025-08-19 15:08:22\', \'2025-08-19 15:08:22\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `appointments` (`appointment_code`, `patient_name`, `patient_phone`, `doctor_name`, `date_time`, `type`, `status`, `notes`, `created_at`, `updated_at`) VALUES (NULL, \'dadad\', NULL, \'meow\', \'2025-08-19 14:03\', \'Follow-up\', \'Confirmed\', \'hahahah\', \'2025-08-19 15:08:22\', \'2025-08-19 15:08:22\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `appointments` (`appointment_code`, `patient_name`, `patient_phone`, `doctor_name`, `date_time`, `type`, `status`, `notes`, `created_at`, `updated_at`) VALUES (:appointment_code:, :patient_name:, :patient_phone:, :doctor_name:, :date_time:, :type:, :status:, :notes:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Appointments.php(59): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Appointments->store()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-19 15:08:22 --> [Caused by] mysqli_sql_exception: Unknown column 'notes' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `appointments` (`appointment_code`, `patient_name`, `patient_phone`, `doctor_name`, `date_time`, `type`, `status`, `notes`, `created_at`, `updated_at`) VALUES (NULL, \'dadad\', NULL, \'meow\', \'2025-08-19 14:03\', \'Follow-up\', \'Confirmed\', \'hahahah\', \'2025-08-19 15:08:22\', \'2025-08-19 15:08:22\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `appointments` (`appointment_code`, `patient_name`, `patient_phone`, `doctor_name`, `date_time`, `type`, `status`, `notes`, `created_at`, `updated_at`) VALUES (NULL, \'dadad\', NULL, \'meow\', \'2025-08-19 14:03\', \'Follow-up\', \'Confirmed\', \'hahahah\', \'2025-08-19 15:08:22\', \'2025-08-19 15:08:22\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `appointments` (`appointment_code`, `patient_name`, `patient_phone`, `doctor_name`, `date_time`, `type`, `status`, `notes`, `created_at`, `updated_at`) VALUES (NULL, \'dadad\', NULL, \'meow\', \'2025-08-19 14:03\', \'Follow-up\', \'Confirmed\', \'hahahah\', \'2025-08-19 15:08:22\', \'2025-08-19 15:08:22\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `appointments` (`appointment_code`, `patient_name`, `patient_phone`, `doctor_name`, `date_time`, `type`, `status`, `notes`, `created_at`, `updated_at`) VALUES (:appointment_code:, :patient_name:, :patient_phone:, :doctor_name:, :date_time:, :type:, :status:, :notes:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Appointments.php(59): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Appointments->store()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-19 15:26:57 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/partials/logout_confirm.php"
[Method: GET, Route: billing]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/partials/logout_confirm.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/partials/logout_confirm', [], true)
 3 APPPATH\Views\auth\billing.php(36): view('auth/partials/logout_confirm')
 4 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\WEB_ITE_GROUP4\\app\\Views\\auth\\billing.php')
 5 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/billing', [], true)
 7 APPPATH\Controllers\Billing.php(12): view('auth/billing')
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Billing->index()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Billing))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-19 18:33:44 --> mysqli_sql_exception: Duplicate column name 'role' in C:\xampp\htdocs\hms_group4\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\hms_group4\system\Database\MySQLi\Connection.php(327): mysqli->query('ALTER TABLE `us...', 0)
#1 C:\xampp\htdocs\hms_group4\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('ALTER TABLE `us...')
#2 C:\xampp\htdocs\hms_group4\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('ALTER TABLE `us...')
#3 C:\xampp\htdocs\hms_group4\system\Database\Forge.php(772): CodeIgniter\Database\BaseConnection->query('ALTER TABLE `us...')
#4 C:\xampp\htdocs\hms_group4\app\Database\Migrations\2025-08-19-000003_AddColumnsToUsers.php(32): CodeIgniter\Database\Forge->addColumn('users', Array)
#5 C:\xampp\htdocs\hms_group4\system\Database\MigrationRunner.php(876): App\Database\Migrations\AddColumnsToUsers->up()
#6 C:\xampp\htdocs\hms_group4\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\hms_group4\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\hms_group4\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\hms_group4\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\hms_group4\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#11 C:\xampp\htdocs\hms_group4\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\xampp\htdocs\hms_group4\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-08-19 19:07:00 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/it_backup.php"
[Method: GET, Route: it/backup]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/it_backup.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/it_backup', [], true)
 3 APPPATH\Controllers\It.php(36): view('auth/it_backup')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\It->backup()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\It))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-19 19:07:03 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/it_maintenance.php"
[Method: GET, Route: it/maintenance]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/it_maintenance.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/it_maintenance', [], true)
 3 APPPATH\Controllers\It.php(42): view('auth/it_maintenance')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\It->maintenance()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\It))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-19 19:07:08 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "auth/it_logs.php"
[Method: GET, Route: it/logs]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/it_logs.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/it_logs', [], true)
 3 APPPATH\Controllers\It.php(48): view('auth/it_logs')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\It->logs()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\It))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-19 19:36:13 --> mysqli_sql_exception: Table 'san_miguel_hms.security_logs' doesn't exist in C:\xampp\htdocs\hms_group4\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\hms_group4\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\hms_group4\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\hms_group4\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\hms_group4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\hms_group4\system\Model.php(213): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\hms_group4\system\BaseModel.php(611): CodeIgniter\Model->doFind(false, NULL)
#6 C:\xampp\htdocs\hms_group4\app\Controllers\It.php(22): CodeIgniter\BaseModel->find()
#7 C:\xampp\htdocs\hms_group4\system\CodeIgniter.php(933): App\Controllers\It->index()
#8 C:\xampp\htdocs\hms_group4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\It))
#9 C:\xampp\htdocs\hms_group4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\hms_group4\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\hms_group4\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\hms_group4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
ERROR - 2025-08-19 19:36:15 --> mysqli_sql_exception: Table 'san_miguel_hms.security_logs' doesn't exist in C:\xampp\htdocs\hms_group4\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\hms_group4\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\hms_group4\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\hms_group4\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\hms_group4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\hms_group4\system\Model.php(213): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\hms_group4\system\BaseModel.php(611): CodeIgniter\Model->doFind(false, NULL)
#6 C:\xampp\htdocs\hms_group4\app\Controllers\It.php(22): CodeIgniter\BaseModel->find()
#7 C:\xampp\htdocs\hms_group4\system\CodeIgniter.php(933): App\Controllers\It->index()
#8 C:\xampp\htdocs\hms_group4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\It))
#9 C:\xampp\htdocs\hms_group4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\hms_group4\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\hms_group4\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\hms_group4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
ERROR - 2025-08-19 19:36:17 --> mysqli_sql_exception: Table 'san_miguel_hms.security_logs' doesn't exist in C:\xampp\htdocs\hms_group4\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\hms_group4\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\hms_group4\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\hms_group4\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\hms_group4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\hms_group4\system\Model.php(213): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\hms_group4\system\BaseModel.php(611): CodeIgniter\Model->doFind(false, NULL)
#6 C:\xampp\htdocs\hms_group4\app\Controllers\It.php(22): CodeIgniter\BaseModel->find()
#7 C:\xampp\htdocs\hms_group4\system\CodeIgniter.php(933): App\Controllers\It->index()
#8 C:\xampp\htdocs\hms_group4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\It))
#9 C:\xampp\htdocs\hms_group4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\hms_group4\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\hms_group4\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\hms_group4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
ERROR - 2025-08-19 19:36:18 --> mysqli_sql_exception: Table 'san_miguel_hms.security_logs' doesn't exist in C:\xampp\htdocs\hms_group4\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\hms_group4\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\hms_group4\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\hms_group4\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\hms_group4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\hms_group4\system\Model.php(213): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\hms_group4\system\BaseModel.php(611): CodeIgniter\Model->doFind(false, NULL)
#6 C:\xampp\htdocs\hms_group4\app\Controllers\It.php(22): CodeIgniter\BaseModel->find()
#7 C:\xampp\htdocs\hms_group4\system\CodeIgniter.php(933): App\Controllers\It->index()
#8 C:\xampp\htdocs\hms_group4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\It))
#9 C:\xampp\htdocs\hms_group4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\hms_group4\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\hms_group4\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\hms_group4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
ERROR - 2025-08-19 19:36:28 --> mysqli_sql_exception: Table 'san_miguel_hms.security_logs' doesn't exist in C:\xampp\htdocs\hms_group4\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\hms_group4\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\hms_group4\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\hms_group4\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\hms_group4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\hms_group4\system\Model.php(213): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\hms_group4\system\BaseModel.php(611): CodeIgniter\Model->doFind(false, NULL)
#6 C:\xampp\htdocs\hms_group4\app\Controllers\It.php(22): CodeIgniter\BaseModel->find()
#7 C:\xampp\htdocs\hms_group4\system\CodeIgniter.php(933): App\Controllers\It->index()
#8 C:\xampp\htdocs\hms_group4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\It))
#9 C:\xampp\htdocs\hms_group4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\hms_group4\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\hms_group4\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\hms_group4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
